In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import csv 
from functools import reduce

In [11]:
with open('./sources/sample.csv', 'w') as file:
    for i in range(1, 11):
        file.write(reduce(lambda a, b: a + b, [f"{j*i}," for j in range(1, 11)])[:-1] + "\n")

In [13]:
df = pd.read_csv("./sources/sample.csv")

In [14]:
df

    1   2   3   4   5   6   7   8   9   10
0   2   4   6   8  10  12  14  16  18   20
1   3   6   9  12  15  18  21  24  27   30
2   4   8  12  16  20  24  28  32  36   40
3   5  10  15  20  25  30  35  40  45   50
4   6  12  18  24  30  36  42  48  54   60
5   7  14  21  28  35  42  49  56  63   70
6   8  16  24  32  40  48  56  64  72   80
7   9  18  27  36  45  54  63  72  81   90
8  10  20  30  40  50  60  70  80  90  100